version: '3.8'

services:
  back:
    build: .
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 80
    volumes:
      - .:/fastapi_photo
    ports:
      - 80
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fastapi-postgres
    expose:
      - 5432

volumes:
  postgres_data: